name: Terraform Infra CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Terraform Init
        run: |
          echo "Initializing Terraform"

      - name: Terraform Validate
        run: |
          echo "Validating Terraform"

      - name: Terraform Plan
        run: |
          echo "Planning Terraform"

      - name: Terraform Apply (Simulated)
        run: |
          echo "Applying Terraform (Simulated)"